In [1]:
from google.colab import drive
print("Import successful")

Import successful


## Importing Packages

In [2]:
import pandas as pd
import numpy as np
from sklearn import metrics
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

## Reading CSV files


In [3]:
dataset1=pd.read_csv('/content/drive/MyDrive/sdl_project/csv Files/Bitcoin Cash.csv')
dataset2=pd.read_csv('/content/drive/MyDrive/sdl_project/csv Files/Bitcoin SV US Dollar.csv')
dataset3=pd.read_csv('/content/drive/MyDrive/sdl_project/csv Files/Ethereum.csv')
dataset4=pd.read_csv('/content/drive/MyDrive/sdl_project/csv Files/Litecoin.csv')

# Bitcoin Cash

In [6]:
dataset1['DATE'] = pd.to_datetime(dataset1.DATE)

In [7]:
X1  = dataset1[['OPEN','HIGH','LOW']]
y1 = dataset1['PRICE']

In [8]:
X1_train , X1_test , y1_train , y1_test = train_test_split(X1,y1,random_state = 0)
regressor1 = LinearRegression()
regressor1.fit(X1_train,y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
print(X1_train[:])
print(X1_test[:])

       OPEN    HIGH     LOW
109  238.15  239.77  232.73
487  417.00  441.96  404.12
101  222.78  226.24  222.35
489  479.30  519.18  456.72
533  355.54  402.31  347.97
..      ...     ...     ...
359  289.68  303.60  282.98
192  231.82  247.45  231.63
629  117.07  122.53  111.36
559  315.38  319.86  303.30
684  100.83  101.26   92.31

[533 rows x 3 columns]
       OPEN    HIGH     LOW
338  215.16  216.10  201.18
142  253.25  255.86  245.56
242  324.42  329.19  299.80
235  337.18  352.29  332.54
468  282.13  308.15  274.01
..      ...     ...     ...
214  227.75  233.05  211.62
399  292.10  295.26  243.11
77   302.38  305.60  269.99
215  220.65  228.14  219.21
492  480.14  500.40  473.14

[178 rows x 3 columns]


In [10]:
print(regressor1.coef_)
print(regressor1.intercept_)

[-0.49284111  0.69678413  0.80574351]
-1.05033677664008


In [11]:
predicted_btc=regressor1.predict(X1_test)

In [12]:
dframe=pd.DataFrame(y1_test,predicted_btc)

In [13]:
dfr=pd.DataFrame({'Actual':y1_test,'Predicted':predicted_btc})

In [14]:
regressor1.score(X1_test,y1_test)


0.9923448860500932

In [15]:
graph=dfr.head(20)

In [16]:
3plt1=[];
print("Enter open value for the stock prediction")
plt1.append(float(input()))
print("Enter High value for the stock prediction")
plt1.append(float(input()))
print("Enter Low value for the stock prediction")
plt1.append(float(input()))
print(plt)

Enter open value for the stock prediction
332
Enter High value for the stock prediction
300
Enter Low value for the stock prediction
292
<module 'matplotlib.pyplot' from '/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py'>


In [17]:
features_btc=np.array([plt1])
print(features_btc)
target_btc=regressor1.predict(features_btc)
print("Predicted price",target_btc)

[[332. 300. 292.]]
Predicted price [279.63875994]


#Bitcoin SV

In [18]:
dataset2['DATE'] = pd.to_datetime(dataset2.DATE)

In [19]:
X2  = dataset2[['OPEN','HIGH','LOW']]
y2= dataset2['PRICE']

In [20]:
X2_train , X2_test , y2_train , y2_test = train_test_split(X2,y2,random_state = 0)

In [21]:
regressor2 = LinearRegression()
regressor2.fit(X2_train,y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
print(regressor2.coef_)
print(regressor2.intercept_)

[-0.59733491  0.84015716  0.75835967]
-0.4475600043139423


In [23]:
predicted_bsv=regressor2.predict(X2_test)

In [24]:
dframe2=pd.DataFrame(y2_test,predicted_bsv)
dfr2=pd.DataFrame({'Actual':y2_test,'Predicted':predicted_bsv})

In [25]:
print(regressor2.score(X2_test,y2_test))

0.9942029356660752


In [26]:
graph=dfr2.head(20)


In [27]:
plt2=[];
print("Enter open value for the stock prediction")
plt2.append(float(input()))
print("Enter High value for the stock prediction")
plt2.append(float(input()))
print("Enter Low value for the stock prediction")
plt2.append(float(input()))

print(plt2)

Enter open value for the stock prediction
243
Enter High value for the stock prediction
250
Enter Low value for the stock prediction
220
[243.0, 250.0, 220.0]


In [28]:
features_bsv=np.array([plt2])
print(features_bsv)
target_bsv=regressor2.predict(features_bsv)
print("Predicted price",target_bsv)

[[243. 250. 220.]]
Predicted price [231.27847342]


# Ethereum

In [29]:
dataset3['DATE'] = pd.to_datetime(dataset3.DATE)

In [30]:
X3=dataset3[['OPEN','HIGH','LOW']]
y3 =dataset3['PRICE']

In [31]:
X3_train , X3_test , y3_train , y3_test = train_test_split(X3,y3,random_state = 0)

In [32]:
regressor3 = LinearRegression()
regressor3.fit(X3_train,y3_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
print(regressor3.coef_)
print(regressor3.intercept_)

[-0.56430244  0.73472997  0.83507604]
0.05063700775909297


In [34]:
predicted_eth=regressor3.predict(X3_test)

In [35]:
dframe3=pd.DataFrame(y3_test,predicted_eth)
dfr3=pd.DataFrame({'Actual':y3_test,'Predicted':predicted_eth})

In [36]:
print(regressor3.score(X3_test,y3_test))

0.9928884520309749


In [37]:
graph=dfr3.head(20)


In [38]:
plt3=[];
print("Enter open value for the stock prediction")
plt3.append(float(input()))
print("Enter High value for the stock prediction")
plt3.append(float(input()))
print("Enter Low value for the stock prediction")
plt3.append(float(input()))
print(plt3)

Enter open value for the stock prediction
220
Enter High value for the stock prediction
24
Enter Low value for the stock prediction
11
[220.0, 24.0, 11.0]


In [39]:
features_eth=np.array([plt3])
print(features_eth)
target_eth=regressor3.predict(features_eth)
print("Predicted price",target_eth)

[[220.  24.  11.]]
Predicted price [-97.27654424]




``
# Litecoin

In [41]:
#dataset4['DATE'] = pd.to_datetime(dataset4.DATE)

In [42]:
X4=dataset4[['OPEN','HIGH','LOW']]
y4=dataset4['PRICE']

In [43]:
X4_train , X4_test , y4_train , y4_test = train_test_split(X4,y4,random_state = 0)

In [44]:
regressor4 = LinearRegression()
regressor4.fit(X4_train,y4_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [45]:
print(regressor4.coef_)
print(regressor4.intercept_)

[-0.40936796  0.63286059  0.78725404]
-0.17818083857849132


In [46]:
predicted_ltc=regressor4.predict(X4_test)

In [47]:
dframe4=pd.DataFrame(y4_test,predicted_ltc)
dfr4=pd.DataFrame({'Actual':y4_test,'Predicted':predicted_ltc})

In [48]:
print(regressor4.score(X4_test,y4_test))

0.9980439270009303


In [49]:
graph=dfr4.head(20)


In [50]:
plt4=[];
print("Enter open value for the stock prediction")
plt4.append(float(input()))
print("Enter High value for the stock prediction")
plt4.append(float(input()))
print("Enter Low value for the stock prediction")
plt4.append(float(input()))
print(plt4)

Enter open value for the stock prediction
330
Enter High value for the stock prediction
350
Enter Low value for the stock prediction
320
[330.0, 350.0, 320.0]


In [51]:
features_ltc=np.array([plt4])
print(features_ltc)
target_ltc=regressor4.predict(features_ltc)
print("Predicted price",target_ltc)

[[330. 350. 320.]]
Predicted price [338.15289146]
